spring.application.name=appNotas

spring.datasource.url=jdbc:postgresql://localhost:5432/devnotas
spring.datasource.username=postgres
spring.datasource.password=mantequilla
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show.-sql=true

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

